_target_: agents.models.flow_matching.rf.RF
_recursive_: false

ln: False
device: ${device}

backbones:
  _target_: agents.backbones.decoder_only.Noise_Dec_only
  _recursive_: false
  state_dim: ${latent_dim}
  action_dim: ${action_dim}
  goal_dim: ${goal_dim}
  goal_conditioned: ${goal_conditioned}
  goal_seq_len: 1
  obs_seq_len: ${obs_tokens}
  action_seq_len: ${act_seq_len}
  embed_pdrob: 0
  # Architecture details
  embed_dim: ${n_embd}
  device: ${device}
  linear_output: true

  use_ada_conditioning: False
  diffusion_type: 'rf'

  encoder:
    _target_: agents.backbones.transformer.blocks.TransformerEncoder
    embed_dim: ${n_embd}
    n_heads: ${n_heads}
    n_layers: ${encoder_n_layer}
    attn_pdrop: 0.3
    resid_pdrop: 0.1
    mlp_pdrop: 0.1
    bias: False