_target_: agents.models.bc.bc.BC_Policy
_recursive_: false

backbones:
  _target_: agents.backbones.decoder_only.Dec_only
  _recursive_: false
  state_dim: ${latent_dim}
  action_dim: ${action_dim}
  goal_dim: ${goal_dim}
  goal_conditioned: ${goal_conditioned}
  goal_seq_len: 1
  obs_seq_len: ${obs_tokens}
  action_seq_len: ${act_seq_len}
  embed_pdrob: 0
  # Architecture details
  embed_dim: ${n_embd}
  device: ${device}
  linear_output: true

  encoder:
    _target_: agents.backbones.mamba.mamba.MixerModel
    ssm_cfg: ${mamba_encoder_cfg}
    d_model: ${n_embd}
    n_layer: ${mamba_n_layer_encoder}
    d_intermediate: ${n_embd}
    device: ${device}

device: ${device}

